version: "3.7"
services:
  db:
    image: postgres:13.3
    restart: unless-stopped
    tty: true
    ports:
      - "5435:${POSTGRES_PORT}"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data/
#  server:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file: .env
#    depends_on:
#      - database
#    networks:
#      - default
#    ports:
#      - "8080:8080"
volumes:
  data:
