version: "3.7"
services:
  db:
    image: postgres:13.3
    restart: unless-stopped
    tty: true
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data/
  app:
    build: ./containers/v1
    container_name: app
    image: app
    ports:
      - "8086:8080"
    depends_on:
      - db

volumes:
  data: