// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ProblemInterface interface {
	IsProblemInterface()
}

type UserCreateResult interface {
	IsUserCreateResult()
}

type UserFindResult interface {
	IsUserFindResult()
}

type UserResolvingResult interface {
	IsUserResolvingResult()
}

type EmailValidationProblem struct {
	Message string `json:"message"`
}

func (EmailValidationProblem) IsProblemInterface()    {}
func (EmailValidationProblem) IsUserResolvingResult() {}

type InternalErrorProblem struct {
	Message string `json:"message"`
}

func (InternalErrorProblem) IsProblemInterface()    {}
func (InternalErrorProblem) IsUserResolvingResult() {}
func (InternalErrorProblem) IsUserCreateResult()    {}
func (InternalErrorProblem) IsUserFindResult()      {}

type NotFoundProblem struct {
	Message string `json:"message"`
}

func (NotFoundProblem) IsProblemInterface() {}
func (NotFoundProblem) IsUserFindResult()   {}

type User struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Email    string `json:"email"`
}

func (User) IsUserResolvingResult() {}

type UserCreateInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type UserCreateOk struct {
	User *User `json:"user"`
}

func (UserCreateOk) IsUserCreateResult() {}

type UserFindOk struct {
	User *User `json:"user"`
}

func (UserFindOk) IsUserFindResult() {}

type UserMutation struct {
	Create UserCreateResult `json:"create"`
}

type UserQuery struct {
	FindByID *User `json:"findById"`
}
